### ISSUE TITLE
We need a `~/.config/maestro/`

### ISSUE THREAD

**Issue by johnisom** [maestro-framework/maestro#15]
Create maestro config directory located at `~/.config/maestro/` or something similar to hold things like AWS account ID and default region. 

Maybe it needs to be a `~/.maestro/` directory. Depends on our exact use case.

For now, just `~/.config/maestro/`.

**Comment by T-monius** [comment]
I propose a file at `~/.config/maestro/aws_account_num.json` with the following contents:
```
{
  "account_number": "xxxx-xxxx-xxxx"
}
```

**Comment by johnisom** [comment]
> I propose a file at `~/.config/maestro/aws_account_num.json` with the following contents:
> 
> ```
> {
>   "account_number": "xxxx-xxxx-xxxx"
> }
> ```

Yes, and it should probably have an aws region as well. Something like this?:

```
{
  "account_number": "xxxxxxxxxxxx",
  "aws_region": "us-east/west-1/2"
```

**Comment by johnisom** [comment]
I think the account number should be stored without the hyphens. They're not used for anything other than pretty display in the AWS Console. Opinions on that?

**Comment by johnisom** [comment]
Also, it may help to have `region` and `account_number` prepended with `aws_` to signify that these are aws configs specifically, not maestro

**Comment by johnisom** [comment]
> Also, it may help to have `region` and `account_number` prepended with `aws_` to signify that these are aws configs specifically, not maestro

Or, depending on how the file is named (such as 'aws_account_num.json'), this isn't necesarry. Though I do think it makes sense to include the `region` in the same file and to get rid of any hyphens.

**Comment by zklamm** [comment]
I'm fine with having the region be in the same file as the account number. The file could then be called `aws_account_info` or similiar.

**Comment by T-monius** [comment]
Agreed.

**Comment by johnisom** [comment]
How do you feel about removing the hyphens @T-monius ?

**Comment by T-monius** [comment]
Agreed
