### ISSUE TITLE
Create a 'maestro new' command

### ISSUE THREAD

**Issue by zklamm** [maestro-framework/maestro#43]
`maestro new <PROJECT_NAME>` prompts user to choose a template, if any.

(optional flag) --template <TEMPLATE_NAME>

This command will create the root directory of the project for you.

**Comment by johnisom** [comment]
Just to note: when a template is not chosen, a `definition.asl.json` is created for you with this content:

``` json
{}
```

A `README.md` is created for you with this content:

``` markdown
# <TITLEIZED_PROJECT_NAME>

```

And a `lambdas` directory is created and empty; and a git repository is init'ed (`git init <PROJECT_NAME>`).
